browsers = [{"platform": "OS X 10.11",
             "browserName": "Safari",
             "version": "9"},
            {"platform": "OS X 10.11",
             "browserName": "chrome",
             "version": "beta"},
            {"platform": "OS X 10.11",
             "browserName": "chrome",
             "version": ""},
            {"platform": "OS X 10.11",
             "browserName": "firefox",
             "version": "beta"},
            {"platform": "OS X 10.11",
             "browserName": "firefox",
             "version": ""},
            {"platform": "Windows 7",
             "browserName": "chrome",
             "version": "beta"},
            {"platform": "Windows 7",
             "browserName": "chrome",
             "version": ""},
            {"platform": "Windows 7",
             "browserName": "firefox",
             "version": ""},
            {"platform": "Windows 7",
             "browserName": "firefox",
             "version": "beta"},
            {"platform": "Windows 7",
             "browserName": "internet explorer",
             "version": "9"},
            {"platform": "Windows 7",
             "browserName": "internet explorer",
             "version": "10"},
            {"platform": "Windows 7",
             "browserName": "internet explorer",
             "version": "11"}]